
###############################################################################
#
# Inclusive Makefile for the x86_64_inventec_d5254 module.
#
# Autogenerated 2017-09-21 08:59:41.534569
#
###############################################################################
x86_64_inventec_d5254_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_inventec_d5254_BASEDIR)module/make.mk
include $(x86_64_inventec_d5254_BASEDIR)module/src/make.mk
include $(x86_64_inventec_d5254_BASEDIR)module/auto/make.mk

