
###############################################################################
#
# Inclusive Makefile for the x86_64_inventec_d10056 module.
#
# Autogenerated 2019-01-10 01:38:48.195620
#
###############################################################################
x86_64_inventec_d10056_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_inventec_d10056_BASEDIR)module/make.mk
include $(x86_64_inventec_d10056_BASEDIR)module/auto/make.mk
include $(x86_64_inventec_d10056_BASEDIR)module/src/make.mk

