
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-inventec-d10056 module.
#
# Autogenerated 2019-01-10 01:38:54.473745
#
###############################################################################
libonlp-x86-64-inventec-d10056_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

