
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-inventec-d7264q28b module.
#
# Autogenerated 2018-09-14 04:12:12.272196
#
###############################################################################
libonlp-x86-64-inventec-d7264q28b_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

