
###############################################################################
#
# Inclusive Makefile for the x86_64_lenovo_ne1064t module.
#
# Autogenerated 2018-11-30 07:22:11.055018
#
###############################################################################
x86_64_lenovo_ne1064t_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_lenovo_ne1064t_BASEDIR)module/make.mk
include $(x86_64_lenovo_ne1064t_BASEDIR)module/src/make.mk
include $(x86_64_lenovo_ne1064t_BASEDIR)module/auto/make.mk

