
###############################################################################
#
# Inclusive Makefile for the libonlp-arm-inventec-d2428 module.
#
# Autogenerated 2016-07-20 18:29:31.706331
#
###############################################################################
libonlp-arm-inventec-d2428_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

