
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-inventec-d5256 module.
#
# Autogenerated 2019-01-10 01:38:54.473745
#
###############################################################################
libonlp-x86-64-inventec-d5256_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

