
###############################################################################
#
# Inclusive Makefile for the x86_64_inventec_d7264q28b module.
#
# Autogenerated 2018-09-14 04:12:06.571804
#
###############################################################################
x86_64_inventec_d7264q28b_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_inventec_d7264q28b_BASEDIR)module/make.mk
include $(x86_64_inventec_d7264q28b_BASEDIR)module/src/make.mk
include $(x86_64_inventec_d7264q28b_BASEDIR)module/auto/make.mk

