
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-inventec-d5264q28b module.
#
# Autogenerated 2018-05-29 02:18:02.735016
#
###############################################################################
libonlp-x86-64-inventec-d5264q28b_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

