
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-inventec-d5264q28b module.
#
# Autogenerated 2017-09-21 08:59:45.115655
#
###############################################################################
libonlp-x86-64-inventec-d5264q28b_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

